# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

variables:
  var1: defaultName

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      displayName: "Display what is in the Build.SourcesDirectory"
      ls -laR --ignore=".git" $(Build.SourcesDirectory)

  - task: AzureCLI@2
    displayName: Deploy Storage Account
    inputs:
      azureSubscription: azure-a104-course
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        stgName = $(az deployment group create \
        --resource-group newrg \
        --name stg.deploy.002 \
        --template-file "$(Build.SourcesDirectory)/main.bicep" \
        --parameters storageAccountName=yzstgname \
        --query properties.outputs.storageAccountName.value -o tsv)
        echo $stgName
        echo "##vso[task.setvariable variable=var1;]$stgName"

  - script: |
      echo "var1= $(var1)"
